# Generated by Django 3.0.2 on 2020-01-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0004_auto_20200117_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='parent',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
