# Generated by Django 3.0.2 on 2020-01-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0006_auto_20200117_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='child_num',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additional',
            name='parent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additional',
            name='school',
            field=models.CharField(blank=True, choices=[('elementary', '초등학교 졸업'), ('middle', '중학교 졸업'), ('high', '고등학교 졸업'), ('college', '대학교(2년제)졸업'), ('university', '대학교(4년제)졸업'), ('graduate', '대학원 졸업 이상'), ('others', '기타')], default='elementary', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additional',
            name='sibling',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
